# opencv colors are BGR

from dims import MAX

face_colors = {}


def random_color():
    """Return a 3-tuple of integers in the ranges 0-255."""
    return (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))


def face(pair: list):
    """Given a face identified by its two dimensions, return its color.

    Colors are generated by blending the colors of the two sides and cached
    in a dictionary.
    """
    assert len(pair) == 2
    # convert the pair of dimensions into a hashable type
    key = tuple(pair)
    if key not in face_colors:
        color0 = bgr[pair[0]]
        color1 = bgr[pair[1]]
        blend = []
        for c in range(3):
            blend.append((color0[c] + color1[c]) // 2)
        face_colors[key] = blend
    return face_colors[key]


def hex_to_rgb(s):
    """Convert a string of 6 hex values into an RGB 3-tuple."""
    return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)


def hex_to_bgr(s):
    """Convert a string of 6 hex values into a BGR 3-tuple."""
    return int(s[4:6], 16), int(s[2:4], 16), int(s[0:2], 16)


# These colors are in the opencv format of BGR
node = (255, 255, 255)
center = (255, 255, 255)
vp = (244, 208, 140)  # vanishing point: a shade of aqua
text = (200, 200, 250)
bg = (0, 0, 0)  # must be zeros so we can fade to black in .draw()
names = (
    ("ff0000", "red"),
    ("ffffff", "white"),
    ("00a8ec", "blue"),
    ("00ff00", "green"),
    ("00ffff", "aqua"),
    ("ffff00", "yellow"),
    ("ff00ff", "fuschia"),
    ("ff8000", "orange"),
    ("800080", "purple"),
    ("e62b86", "pink"),
    ("f1a629", "lt.orange"),
    ("fff99d", "lemon yellow"),
    ("8dcb41", "lt. green"),
    ("bfb2d3", "lilac"),
    ("826b89", "purple"),
    ("c0c0c0", "silver"),
)
assert len(names) >= MAX    # Yes, there can be more colors than necessary
ascii = [name[0] for name in names]
name = [name[1] for name in names]
html = ["#" + s for s in ascii]
bgr = [hex_to_bgr(c) for c in ascii]
